
--Ej 2

-- Tabla    CUENTA

CREATE TABLE CUENTA 
(
  NUMERO NUMBER NOT NULL 
, NOMBRE VARCHAR2(80) 
, DIRECCION VARCHAR2(100) 
, CIUDAD VARCHAR2(60) 
, FONO VARCHAR2(30) 
, SALDO NUMBER 
, CONSTRAINT CUENTA_PK PRIMARY KEY 
  (
    NUMERO 
  )
  ENABLE 
);

-- Tabla MOVIMIENTO

CREATE TABLE MOVIMIENTO 
(
  NUMERO NUMBER 
, OPERACION VARCHAR2(1) 
, NOMBRE VARCHAR2(80) 
, DIRECCION VARCHAR2(100) 
, CIUDAD VARCHAR2(60) 
, FONO VARCHAR2(30) 
, SALDO NUMBER 
);

-- Datos de Prueba

INSERT INTO "SYSTEM"."CUENTA" (NUMERO, NOMBRE, DIRECCION, CIUDAD, FONO, SALDO) VALUES ('111', 'ignacio', 'bajo el puente', 'antofagasta', '123456', '100000')
INSERT INTO "SYSTEM"."CUENTA" (NUMERO, NOMBRE, DIRECCION, CIUDAD, FONO, SALDO) VALUES ('222', 'carmen', 'casa carmen', 'valparaiso', '654321', '20000')
INSERT INTO "SYSTEM"."CUENTA" (NUMERO, NOMBRE, DIRECCION, CIUDAD, FONO, SALDO) VALUES ('333', 'solaris', 'sol', 'bialactea', '555555', '222222')

INSERT INTO "SYSTEM"."MOVIMIENTO" (NUMERO, OPERACION, NOMBRE, DIRECCION, CIUDAD, FONO, SALDO) VALUES ('6273', 'I', 'JOSE FUENTES SAVEEDRA', 'LATORRE 2210', 'ANTOFAGASTA', '55-214411', '200000')
INSERT INTO "SYSTEM"."MOVIMIENTO" (NUMERO, OPERACION, SALDO) VALUES ('111', 'U', '999999')
INSERT INTO "SYSTEM"."MOVIMIENTO" (NUMERO, OPERACION) VALUES ('333', 'D')
INSERT INTO "SYSTEM"."MOVIMIENTO" (NUMERO, OPERACION, NOMBRE, DIRECCION, CIUDAD, FONO, SALDO) VALUES ('222', 'I', 'MARCO', 'POLO', 'SANTIAGO', '55-334455', '442555')
INSERT INTO "SYSTEM"."MOVIMIENTO" (NUMERO, OPERACION, NOMBRE, DIRECCION, SALDO) VALUES ('777', 'U', 'DIEGO', 'XML', '3232')
INSERT INTO "SYSTEM"."MOVIMIENTO" (NUMERO, OPERACION) VALUES ('888', 'D')


-- Bloque

